trigger:
  batch: true
  branches:
    include:
    - master
    - 3.?*
    exclude:
    - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
- group: codecov

stages:
- template: stage-lint.yml
- template: stage-test.yml
  parameters:
    codecov.token: '$(codecov.token)'
